import { hightWindow } from "../../../Constants";
import {StyleSheet} from "react-native";


export const stylesUserSeguindoSeguidor=StyleSheet.create({
    container:
    {
        display:"flex",
        height:hightWindow,
        backgroundColor:"#1E1F1E"
    },
    areaContent:
    {    
       display:"flex",
       flexDirection:"column"         
    },
    areaMenu:
     {
         display:"flex",
         flexDirection:"row",        
         height:80,
         width:"100%",     
         bottom:0,
         overflow:"hidden",       
         position:"absolute"    
    },
    header:
    {
        height:45,
        width:"100%",
        padding:10,
        display:"flex",
        flexDirection:"row",
        justifyContent:"space-between",
        overflow:"hidden"
    },
    textLow:
    {
        color:"white",
        fontFamily: 'Montserrat',
    },
    exit:
    {
        display:"flex",
        flexDirection:"row"
    },
    TextHashTag:
    {
        color:"white",
        fontFamily:'Oswald',       
    },
    marca:
    {
        height:35,
        width:10,
        backgroundColor:"#FDCF09",
        marginRight:10,
        borderTopRightRadius:5,
        borderBottomRightRadius:5
    },
    marcaRegion:
    {
        backgroundColor:"#282828",
        display:"flex",
        flexDirection:"row",
        alignItems:"center",
        paddingTop:20,
        paddingBottom:10        
    },
    marcaRegion2:
    {
       
        display:"flex",
        flexDirection:"row",
        alignItems:"center",
        paddingTop:20,
        paddingBottom:10        
    },
    textRegionLow:
    {
        backgroundColor:"#282828",
        display:"flex",
        flexDirection:"column",
        paddingLeft:15,
        paddingBottom:10
    },
    textRegionLow2:
    {
        
        display:"flex",
        flexDirection:"column",
        paddingLeft:15,
        paddingRight:15,
        textAlign:"justify",
        paddingBottom:40
    },
    areaImg:
    {
        height:180,
        display:"flex",
        flexDirection:"column",
        alignItems:"center",
        justifyContent:"center"
        
    },
    region1:
    {
        height:90,
        width:"100%",
        position:"relative"        
    },
    region2:
    {
        height:90,
        width:"100%",
        backgroundColor:"#282828",
        position:"relative"        
    },
    regionDates:
    {
        backgroundColor:"#373837",
        height:100,
        display:"flex",
        flexDirection:"row",
        width:"100%"

    },
    backImg:
    {
        backgroundColor:"white",
        borderRadius:75,
        height:150,
        width:150,
        display:"flex",
        flexDirection:"row",
        alignItems:"center",
        justifyContent:"center",
        position:"absolute"
      
    },
    img:
    {
        width:140,
        height:140,
        borderRadius:70
    },
    dateRegion:
    {
        display:"flex",
        flexDirection:"column",
        alignItems:"center",
        justifyContent:"center",
        flex:1
    },
    textHigh:
    {
        fontFamily:"Oswald",
        fontSize:21,
        color:"white"
    }
});